# Generated by Django 5.0.2 on 2024-04-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_data',
            name='recipe_para',
        ),
    ]
